language: java
jdk:
  - oraclejdk8
dist: trusty
stages:
  - gen
  - build
install: true
script:
  - 'mvn package -P public,refresh -q'
  - 'mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=API4KBs_kmdp-api -Ppublic,normal -q'
deploy:
  provider: script
  script: mvn clean deploy -DskipTests -Ppublic,normal -s .travis.settings.xml -q
  skip_cleanup: true

addons:
  sonarcloud:
    organization: "api4kbs"
    token:
      secure: "G7d5DqaSVD2cSH/miVPgl0OnDm4V3t4TCTloi9mniniPCg6dfZVvgteGiDFFxr4L9lghQAAeeZrB2FwVcgy2AMK40WmfC9fQzJU7ue1Cbk2UaMKc84dmhsGY5o6Qdr2WkFMzxOiQ6BjxAUXa4OwZsaz2r7QBHd6gh790+Y6l+zdtM5IucdlvhopOcPDNc9a0yqzz9AhsZaar/BMHUyZ2HMWwoMG7tDx2oss/lzPmLxtjHDwrSggFUMmGFwXhGFjiUV/iGhC0Lr+fxfrIGBNMGKAAcf9MuB37neHZv2f8sXp87mEVP22YnbP+A5ahB0Eko5uqzxeTcAy2r1Bcplx2WCkjJa2bsIV0LYD2rAYKf2lsgCto6in9v4FdYTm34b+XprZAsVKHsQsUEoPYym5JWAmF9lW4VwsuoaUJcYvGeT/+RQ1B3XzUyydwNWarpPzHVqgl7PWIZm9c4nrSOlN0McvxVjmyfM4fS5bsz3j6U06yyz7h94d7HAvgC7xhhJTJRc2CgL2zkVBx3Z9fHOIKO7hafK9+4jfoABev2OCiv5Kw8nlydgO1cdDBcPURJ+Qcxxb/wissKI9srbQIjJaRl8Xrn6kZAr7KWfULz4zpkOeuZKgZa6padnkGPo98cYStkmfKjpr3VfXr589R43jZ6ruAirT5nLY39H/8V8EkvVk="

env:
  global:
  - secure: CpAbaZp4Yz9Hbmj2pqDUMSivV9E3ZBfrsZFv26t/axWXLRNgzpOHn9sCiF/QpHggOYPbC2iBMbv4neALOT7j7S7pV1xutUi88fhk12cRjADhS/NBuC9tpXF/LbkH6iadqz8sgTkm5BEnpoLSHWf2+44Lu0jE4TgHNFtdd/B8n+nux4IvvhgCXO+5gXG6Zm7Dhbd4Fs0AGt2yI83QS1DysYGZtETEL2Ei1e/3CYEo3POJDw14wsKEpTiEIvav+suq7XTrNh5CpW0CC8+/5Ny7uMJmrliHwVAlXtxpbQT1EUAzGs4DlvkHtuxFhT7Xhv6mQNtuIqNAOhFnMdk7t5CFM3SKZLGNlCZpYFGA+GvIeDGGuLMXX9QQaK6cR1fFGOk2/S00cWf/yYJwETZCy0c4IHSXQ3aSYPZKlcuURWD2ZYaG1RpDTlj530/0PyKw05tyG5WyGTINcZ08KrCa1jFfO+h3TgvrJaKwMPR2W0ItNCgMI8oTQ3pd4ZxbrahL0WiRivUExslSMGUyOz9MBqUMC39KHalFA53on7xqUp/mz3gUdWC+hpTfDlzDEumnU+574b8AuOcBzMSkLuTeL/o6kzsywGqI2g2HLzLbpmA6kYGR/V3PlzusgGt5pE8vX9rMus82EJqv75RrVl+9lQK9F/LjdPldWNxRoDplF5OvL48=
  - secure: G5b0yGrAzADbr6rZtp3Hs8aNoP7TwD5pIVprm5fxHsSnsGZddciTmpR4phSkIW19LWwjmM50A5c+EcCoekN4bEVPFbr42R2y7PGti+lcJr39oGLNHM7GtIu/yeVtlqG8wKzyRtHow+cunzy20qZefjWcdU9qB/JE1UaWqRnSRGzgblYRofccDYy1l/z0FGHJJB9AAJO7JkUM73bN4pIrRNY4VbmLya/526aPaX0T81wmF9l93kZWXFDDhGZKrbaP3EuPYUfClpdA6tBhUkvWfqW/eSB7yLxByStfzYoKEHSFSHfbxfOUcqeRwryt5jnkxK5mqNzJj3Xb5OX3valj3lEJ4TnWbmYcmYhHweWSLbgZbAKCRkDnIiPsr7yykySE5+W5TOsTzI/f4YY9+YZIk96+7Pck1t2iRcyaaukwDYN0ACa69qMOsgvMtI6w2PojFjbgIL5Hg4H1nMfIHvUQXvk5pu2OEPALzqKF2wYjQFsB+/f5/WtigtMwhGN9zc3mJjHW7K4EbMopFXMCrfjf6kI18MxFpkXOnXCme4Mn/Se6FVViBQmGXPxAeTHDSa+NDS67zbqnk8wTeO1X44ep3lobTQlnTmceR19XBwQyeF2Z+hNkOVCqcz0Z3oLN71K/qJ8gonMkdz7UlEaUDsr9nWN+0VD6GKRpoaAzYUkvu0I=
  - secure: Rv1W3NhPGXVXziys5rsy77fpcpN2ZumCNPnvPw8b93C/oydcwHP74bxBjMt3GeIv/KNNPNyeltsK2yLYBamLWtDb+PRK0Mt3TqLLMu5k+mdqgfVgraUU68l7n2iF9/M8nT3JKkcaDSRgfrEfr0AoEVrptrCzI72n/RtnwDL6s9RYnbSObTezu6ewqbVoUC9ft7HhJyItPkE+8l9sWkBeHrTmbKSATXh8095BCcvdNefCge9kRfWCRGh6sEfr/u9IuP5ONAa9HwQK80P/ie4AoOCGgPMsEMBqHOvB5LjCOEpGyD314/n2Cgh8xHinFgjOiO/oyQWD9xqo5EQV/eLbkrNTyukDgGFq5ZhOLI2tHguA5E4ZDDNOtATmG4M2avKSa+eYCD36+mrz47qxi31h+H2t+e0Np+cRztjyFi00MrUQbNCOQZCTf06yF2QkboRqqvYJgBfemZoIOXycvhvMy6/Zi6/j7vjgFmieImzaGFtfvAqqvJ7rzJmvLoQTfT2P08cVdhzUyASklKmnwUekHY9JaRms3/vtlacCtc7IkWob3PVlPoJJSWA3tn0rIrMJbODlbZnLOu8s+7+f5UF4kh/XCBV5vIRJDZsAJzS+g1NVzG9zs1wUnpkI1HbTPgsVi4wL7Y4QeW4FuRRMv53CYKErPRqcHQYfRN7IU/o2JR8=
